-- Generated from supabase/seeds/destination_places.csv by scripts/csv-to-seed-sql.mjs -- do not edit directly.
-- 114 rows in 1 batch(es) of up to 500.

insert into public.destination_places
  (destination, name, category, lat, lng, description, photo_url, source, content_slug)
values
  ('Thailand', 'Grand Palace', 'spot', 13.7500, 100.4913, 'Royal complex in Bangkok housing the revered Emerald Buddha temple.', '', 'editorial', 'thailand:grand-palace'),
  ('Thailand', 'Wat Pho', 'spot', 13.7465, 100.4927, 'Home of the giant reclining Buddha and traditional Thai massage.', '', 'editorial', 'thailand:wat-pho'),
  ('Thailand', 'Wat Arun', 'spot', 13.7437, 100.4889, 'Riverside temple with a porcelain-tiled spire best seen at sunset.', '', 'editorial', 'thailand:wat-arun'),
  ('Thailand', 'Chatuchak Weekend Market', 'shopping', 13.7999, 100.5502, 'Sprawling weekend market with thousands of stalls selling almost everything.', '', 'editorial', 'thailand:chatuchak-weekend-market'),
  ('Thailand', 'ICONSIAM', 'shopping', 13.7264, 100.5100, 'Riverside luxury mall with an indoor floating market food hall.', '', 'editorial', 'thailand:iconsiam'),
  ('Thailand', 'Terminal 21 Asok', 'shopping', 13.7376, 100.5601, 'Airport-themed mall where each floor imitates a different world city.', '', 'editorial', 'thailand:terminal-21-asok'),
  ('Thailand', 'Jodd Fairs Rama 9', 'food', 13.7554, 100.5658, 'Night market famous for volcano pork ribs and cheap seafood.', '', 'editorial', 'thailand:jodd-fairs-rama-9'),
  ('Thailand', 'Yaowarat Chinatown', 'food', 13.7398, 100.5090, 'Bangkok''s Chinatown street-food strip, busiest and best after dark.', '', 'editorial', 'thailand:yaowarat-chinatown'),
  ('Thailand', 'Suvarnabhumi Airport', 'transport', 13.6900, 100.7501, 'Bangkok''s main international airport, linked to the city by Airport Rail Link.', '', 'editorial', 'thailand:suvarnabhumi-airport'),
  ('Thailand', 'Hua Lamphong Station', 'transport', 13.7376, 100.5170, 'Historic Bangkok rail terminus, now a heritage hub beside the MRT.', '', 'editorial', 'thailand:hua-lamphong-station'),
  ('Thailand', 'Asiatique The Riverfront', 'shopping', 13.7047, 100.5029, 'Open-air riverside night market with a Ferris wheel and restaurants.', '', 'editorial', 'thailand:asiatique-the-riverfront'),
  ('Thailand', 'Wat Phra That Doi Suthep', 'spot', 18.8047, 98.9217, 'Golden mountain temple above Chiang Mai with sweeping valley views.', '', 'editorial', 'thailand:wat-phra-that-doi-suthep'),
  ('Thailand', 'Nimman Road', 'food', 18.7967, 98.9670, 'Chiang Mai''s cafe and dining street, popular with digital nomads.', '', 'editorial', 'thailand:nimman-road'),
  ('Thailand', 'Patong Beach', 'spot', 7.8965, 98.2960, 'Phuket''s busiest beach, lined with water sports, bars and hotels.', '', 'editorial', 'thailand:patong-beach'),
  ('Thailand', 'Ayutthaya Historical Park', 'spot', 14.3567, 100.5340, 'UNESCO ruins of Siam''s old capital, an easy day trip north.', '', 'editorial', 'thailand:ayutthaya-historical-park'),
  ('Vietnam', 'Hoan Kiem Lake', 'spot', 21.0287, 105.8524, 'Hanoi''s central lake with Ngoc Son Temple on a small island.', '', 'editorial', 'vietnam:hoan-kiem-lake'),
  ('Vietnam', 'Ho Chi Minh Mausoleum', 'spot', 21.0367, 105.8347, 'Solemn granite memorial in Ba Dinh Square, strict dress code applies.', '', 'editorial', 'vietnam:ho-chi-minh-mausoleum'),
  ('Vietnam', 'Ben Thanh Market', 'shopping', 10.7724, 106.6980, 'Landmark Saigon market for souvenirs, fabric, coffee and street snacks.', '', 'editorial', 'vietnam:ben-thanh-market'),
  ('Vietnam', 'War Remnants Museum', 'spot', 10.7797, 106.6923, 'Ho Chi Minh City museum documenting the war through photos and vehicles.', '', 'editorial', 'vietnam:war-remnants-museum'),
  ('Vietnam', 'Bui Vien Walking Street', 'food', 10.7670, 106.6930, 'Backpacker street alive each night with cheap beer and grilled food.', '', 'editorial', 'vietnam:bui-vien-walking-street'),
  ('Vietnam', 'Tan Son Nhat Airport', 'transport', 10.8188, 106.6520, 'Ho Chi Minh City''s international airport, about seven kilometres from downtown.', '', 'editorial', 'vietnam:tan-son-nhat-airport'),
  ('Vietnam', 'Ha Long Bay', 'spot', 20.9101, 107.1839, 'Emerald bay of limestone karsts, usually visited on an overnight cruise.', '', 'editorial', 'vietnam:ha-long-bay'),
  ('Vietnam', 'Hoi An Ancient Town', 'spot', 15.8801, 108.3260, 'Lantern-lit trading port, walkable old quarter and fast tailor shops.', '', 'editorial', 'vietnam:hoi-an-ancient-town'),
  ('Vietnam', 'Golden Bridge Ba Na Hills', 'spot', 15.9955, 107.9966, 'Hilltop walkway held by giant stone hands above Da Nang.', '', 'editorial', 'vietnam:golden-bridge-ba-na-hills'),
  ('Vietnam', 'Noi Bai Airport', 'transport', 21.2212, 105.8072, 'Hanoi''s international airport, roughly forty minutes from the Old Quarter.', '', 'editorial', 'vietnam:noi-bai-airport'),
  ('Singapore', 'Marina Bay Sands SkyPark', 'spot', 1.2834, 103.8607, 'Rooftop observation deck over the bay, the city''s signature skyline view.', '', 'editorial', 'singapore:marina-bay-sands-skypark'),
  ('Singapore', 'Gardens by the Bay', 'spot', 1.2816, 103.8636, 'Supertree grove and cooled domes, free light show every evening.', '', 'editorial', 'singapore:gardens-by-the-bay'),
  ('Singapore', 'Merlion Park', 'spot', 1.2868, 103.8545, 'Waterfront statue of Singapore''s lion-fish mascot facing Marina Bay.', '', 'editorial', 'singapore:merlion-park'),
  ('Singapore', 'Sentosa Island', 'spot', 1.2494, 103.8303, 'Resort island with beaches, Universal Studios and cable car access.', '', 'editorial', 'singapore:sentosa-island'),
  ('Singapore', 'Orchard Road', 'shopping', 1.3040, 103.8318, 'Singapore''s main shopping boulevard, malls stacked end to end.', '', 'editorial', 'singapore:orchard-road'),
  ('Singapore', 'Maxwell Food Centre', 'food', 1.2805, 103.8449, 'Classic hawker centre in Chinatown, famous for Hainanese chicken rice.', '', 'editorial', 'singapore:maxwell-food-centre'),
  ('Singapore', 'Jewel Changi Airport', 'transport', 1.3606, 103.9899, 'Airport mall with the world''s tallest indoor waterfall and gardens.', '', 'editorial', 'singapore:jewel-changi-airport'),
  ('Singapore', 'Bugis Street', 'shopping', 1.3006, 103.8559, 'Budget street market for clothes, accessories and quick local snacks.', '', 'editorial', 'singapore:bugis-street'),
  ('Malaysia', 'Petronas Twin Towers', 'spot', 3.1578, 101.7117, 'Kuala Lumpur''s twin skyscrapers with a skybridge and observation deck.', '', 'editorial', 'malaysia:petronas-twin-towers'),
  ('Malaysia', 'Batu Caves', 'spot', 3.2379, 101.6840, 'Limestone cave temple reached by 272 brightly painted steps.', '', 'editorial', 'malaysia:batu-caves'),
  ('Malaysia', 'Jalan Alor', 'food', 3.1450, 101.7080, 'Kuala Lumpur''s night food street of grilled seafood and satay.', '', 'editorial', 'malaysia:jalan-alor'),
  ('Malaysia', 'Pavilion Bukit Bintang', 'shopping', 3.1488, 101.7133, 'Central Kuala Lumpur mall anchoring the Bukit Bintang shopping district.', '', 'editorial', 'malaysia:pavilion-bukit-bintang'),
  ('Malaysia', 'Kuala Lumpur International Airport', 'transport', 2.7456, 101.7099, 'Malaysia''s main airport, connected to the city by the KLIA Ekspres.', '', 'editorial', 'malaysia:kuala-lumpur-international-airport'),
  ('Malaysia', 'Central Market Kuala Lumpur', 'shopping', 3.1457, 101.6958, 'Art deco hall selling batik, handicrafts and Malaysian souvenirs.', '', 'editorial', 'malaysia:central-market-kuala-lumpur'),
  ('Malaysia', 'Armenian Street George Town', 'spot', 5.4171, 100.3369, 'Penang heritage lane known for its painted street-art murals.', '', 'editorial', 'malaysia:armenian-street-george-town'),
  ('Japan', 'Sensoji Temple', 'spot', 35.7148, 139.7967, 'Tokyo''s oldest temple in Asakusa, approached through Nakamise shopping lane.', '', 'editorial', 'japan:sensoji-temple'),
  ('Japan', 'Shibuya Crossing', 'spot', 35.6595, 139.7005, 'The world''s busiest pedestrian scramble, best watched from above.', '', 'editorial', 'japan:shibuya-crossing'),
  ('Japan', 'Tsukiji Outer Market', 'food', 35.6654, 139.7707, 'Tokyo market lanes serving fresh sushi, tamagoyaki and seafood skewers.', '', 'editorial', 'japan:tsukiji-outer-market'),
  ('Japan', 'Fushimi Inari Taisha', 'spot', 34.9671, 135.7727, 'Kyoto shrine with thousands of vermilion torii gates up the hillside.', '', 'editorial', 'japan:fushimi-inari-taisha'),
  ('Japan', 'Dotonbori', 'food', 34.6687, 135.5013, 'Osaka''s neon canal street, home of takoyaki and okonomiyaki.', '', 'editorial', 'japan:dotonbori'),
  ('South Korea', 'Gyeongbokgung Palace', 'spot', 37.5796, 126.9770, 'Seoul''s main Joseon palace with a daily guard-changing ceremony.', '', 'editorial', 'south-korea:gyeongbokgung-palace'),
  ('South Korea', 'Myeongdong Shopping Street', 'shopping', 37.5636, 126.9827, 'Seoul''s cosmetics and fashion district, packed with street food carts.', '', 'editorial', 'south-korea:myeongdong-shopping-street'),
  ('South Korea', 'N Seoul Tower', 'spot', 37.5512, 126.9882, 'Namsan mountain tower with panoramic city views and love locks.', '', 'editorial', 'south-korea:n-seoul-tower'),
  ('South Korea', 'Gwangjang Market', 'food', 37.5700, 126.9997, 'Historic Seoul market known for bindaetteok pancakes and knife-cut noodles.', '', 'editorial', 'south-korea:gwangjang-market'),
  ('South Korea', 'Incheon International Airport', 'transport', 37.4491, 126.4506, 'Korea''s main gateway, about an hour from central Seoul by train.', '', 'editorial', 'south-korea:incheon-international-airport'),
  ('China', 'Canton Tower', 'spot', 23.1066, 113.3245, 'Guangzhou''s twisting observation tower, best at dusk over the Pearl River.', '', 'editorial', 'china:canton-tower'),
  ('China', 'Shamian Island', 'spot', 23.1069, 113.2419, 'Quiet colonial-era island of shaded avenues, cafes and old consulates.', '', 'editorial', 'china:shamian-island'),
  ('China', 'Chen Clan Ancestral Hall', 'spot', 23.1290, 113.2426, 'Qing-dynasty complex of carved timber and ceramic roof ridges, now a folk art museum.', '', 'editorial', 'china:chen-clan-ancestral-hall'),
  ('China', 'Yuexiu Park', 'spot', 23.1400, 113.2640, 'Guangzhou''s largest central park, with the Five Rams statue and city museum.', '', 'editorial', 'china:yuexiu-park'),
  ('China', 'Beijing Road Pedestrian Street', 'shopping', 23.1250, 113.2680, 'Busy Guangzhou shopping street built over excavated Song-dynasty roadway.', '', 'editorial', 'china:beijing-road-pedestrian-street'),
  ('China', 'Shangxiajiu Pedestrian Street', 'shopping', 23.1189, 113.2450, 'Arcaded Guangzhou street of clothing stalls, snack shops and old teahouses.', '', 'editorial', 'china:shangxiajiu-pedestrian-street'),
  ('China', 'Enning Road', 'food', 23.1180, 113.2380, 'Old Xiguan lane known for double-skin milk, wonton noodles and Cantonese snacks.', '', 'editorial', 'china:enning-road'),
  ('China', 'Guangzhou Baiyun International Airport', 'transport', 23.3924, 113.2988, 'Guangzhou''s international airport, the usual first landing from Phnom Penh.', '', 'editorial', 'china:guangzhou-baiyun-international-airport'),
  ('China', 'Guangzhou South Railway Station', 'transport', 22.9889, 113.2686, 'High-speed rail hub for Shenzhen, Hong Kong, Shanghai and Beijing.', '', 'editorial', 'china:guangzhou-south-railway-station'),
  ('China', 'Tianhe District', 'stay', 23.1247, 113.3610, 'Guangzhou''s modern centre — metro on the doorstep, malls and business hotels.', '', 'editorial', 'china:tianhe-district'),
  ('China', 'The Bund', 'spot', 31.2397, 121.4903, 'Shanghai''s riverside promenade, colonial banks on one side and Pudong towers on the other.', '', 'editorial', 'china:the-bund'),
  ('China', 'Yu Garden', 'spot', 31.2270, 121.4920, 'Ming-dynasty walled garden of rockeries and ponds, beside a busy bazaar.', '', 'editorial', 'china:yu-garden'),
  ('China', 'Oriental Pearl Tower', 'spot', 31.2397, 121.4998, 'Pudong''s landmark tower with a glass floor above the Huangpu River.', '', 'editorial', 'china:oriental-pearl-tower'),
  ('China', 'Nanjing Road', 'shopping', 31.2354, 121.4750, 'Shanghai''s main shopping street, pedestrianised from People''s Square to the Bund.', '', 'editorial', 'china:nanjing-road'),
  ('China', 'Qibao Ancient Town', 'food', 31.1520, 121.3520, 'Canal-side Shanghai old town packed with street-food stalls and snack shops.', '', 'editorial', 'china:qibao-ancient-town'),
  ('China', 'Shanghai Pudong International Airport', 'transport', 31.1443, 121.8083, 'Shanghai''s main international airport, linked to the city by maglev and metro.', '', 'editorial', 'china:shanghai-pudong-international-airport'),
  ('China', 'Forbidden City', 'spot', 39.9163, 116.3972, 'Beijing''s imperial palace complex — book entry online, it sells out days ahead.', '', 'editorial', 'china:forbidden-city'),
  ('China', 'Temple of Heaven', 'spot', 39.8822, 116.4066, 'Ming-dynasty ritual complex set in a park where locals practise tai chi at dawn.', '', 'editorial', 'china:temple-of-heaven'),
  ('China', 'Mutianyu Great Wall', 'spot', 40.4319, 116.5704, 'Restored, less crowded stretch of the Great Wall about two hours from Beijing.', '', 'editorial', 'china:mutianyu-great-wall'),
  ('China', 'Wangfujing Street', 'shopping', 39.9150, 116.4108, 'Beijing''s best-known shopping street, walking distance from the Forbidden City.', '', 'editorial', 'china:wangfujing-street'),
  ('China', 'Beijing Capital International Airport', 'transport', 40.0799, 116.6031, 'Beijing''s older international airport, on the Airport Express metro line.', '', 'editorial', 'china:beijing-capital-international-airport'),
  ('China', 'Dongmen Pedestrian Street', 'shopping', 22.5450, 114.1200, 'Shenzhen''s oldest shopping quarter, cheap clothing and electronics.', '', 'editorial', 'china:dongmen-pedestrian-street'),
  ('China', 'Shenzhen Bao''an International Airport', 'transport', 22.6393, 113.8107, 'Shenzhen''s airport, a common connection point for southern China.', '', 'editorial', 'china:shenzhen-baoan-international-airport'),
  ('China', 'Chengdu Research Base of Giant Panda Breeding', 'spot', 30.7333, 104.1500, 'Go at opening time — the pandas are active early and asleep by midday.', '', 'editorial', 'china:chengdu-research-base-of-giant-panda-breeding'),
  ('China', 'Jinli Ancient Street', 'food', 30.6420, 104.0430, 'Chengdu lane of Sichuan street food, tea houses and evening lanterns.', '', 'editorial', 'china:jinli-ancient-street'),
  ('Thailand', 'Bang Krachao', 'spot', 0, 0, 'A green river peninsula across from Bangkok, reached by ferry and best seen by bicycle.', '', 'editorial', 'thailand:bang-krachao'),
  ('Vietnam', '42 Nguyen Hue', 'spot', 10.7738, 106.7040, 'A 1960s Saigon apartment block whose flats are now small cafes, one per balcony.', '', 'editorial', 'vietnam:42-nguyen-hue'),
  ('Vietnam', 'Marble Mountains', 'spot', 0, 0, 'Limestone and marble hills south of Da Nang, with cave shrines and lookout steps.', '', 'editorial', 'vietnam:marble-mountains'),
  ('Vietnam', 'Hai Van Pass', 'spot', 0, 0, 'The coastal mountain pass between Da Nang and Hue, usually ridden or driven for the views.', '', 'editorial', 'vietnam:hai-van-pass'),
  ('Singapore', 'Mustafa Centre', 'shopping', 0, 0, 'A 24-hour Little India department store known for electronics, gold and groceries.', '', 'editorial', 'singapore:mustafa-centre'),
  ('Singapore', 'Pulau Ubin', 'spot', 0, 0, 'An undeveloped island off the north-east coast, reached by bumboat from Changi Point.', '', 'editorial', 'singapore:pulau-ubin'),
  ('South Korea', 'Ihwa Mural Village', 'spot', 0, 0, 'A hillside Seoul neighbourhood painted with murals and stairways, still residential.', '', 'editorial', 'south-korea:ihwa-mural-village'),
  ('Japan', 'Yanaka Ginza', 'shopping', 0, 0, 'An old-Tokyo shopping street of small independent shops and street-food stalls.', '', 'editorial', 'japan:yanaka-ginza'),
  ('Japan', 'Todoroki Valley', 'spot', 0, 0, 'A short wooded ravine walk inside Tokyo, following a stream below street level.', '', 'editorial', 'japan:todoroki-valley'),
  ('Malaysia', 'Kampung Baru', 'spot', 3.1636, 101.7017, 'A Malay village quarter inside central Kuala Lumpur, busiest for its morning market.', '', 'editorial', 'malaysia:kampung-baru'),
  ('Vietnam', 'Independence Palace', 'spot', 10.7772, 106.6958, 'The 1960s presidential palace, kept as it was left in 1975, war bunker included.', '', 'editorial', 'vietnam:independence-palace'),
  ('Vietnam', 'Notre-Dame Cathedral Saigon', 'spot', 10.7797, 106.6990, 'French-built brick cathedral on the old central square; check restoration works before going.', '', 'editorial', 'vietnam:notre-dame-cathedral-saigon'),
  ('Vietnam', 'Saigon Central Post Office', 'spot', 10.7799, 106.6996, 'A working colonial post office with a vaulted hall and hand-painted wall maps.', '', 'editorial', 'vietnam:saigon-central-post-office'),
  ('Vietnam', 'Bitexco Financial Tower', 'spot', 10.7717, 106.7043, 'Saigon Skydeck on the 49th floor, looking down the bend of the river.', '', 'editorial', 'vietnam:bitexco-financial-tower'),
  ('Vietnam', 'Nguyen Hue Walking Street', 'spot', 10.7743, 106.7038, 'Wide pedestrian boulevard up to the old city hall, at its busiest after dark.', '', 'editorial', 'vietnam:nguyen-hue-walking-street'),
  ('Vietnam', 'Jade Emperor Pagoda', 'spot', 10.7920, 106.6926, 'Dim, incense-thick Taoist temple with carved wood panels, north of District 1.', '', 'editorial', 'vietnam:jade-emperor-pagoda'),
  ('Vietnam', 'Tan Dinh Church', 'spot', 10.7897, 106.6906, 'The pink church on Hai Ba Trung; the photograph is from across the road.', '', 'editorial', 'vietnam:tan-dinh-church'),
  ('Vietnam', 'Landmark 81 SkyView', 'spot', 10.7950, 106.7218, 'Vietnam''s tallest tower, with an observation deck over the river and the city.', '', 'editorial', 'vietnam:landmark-81-skyview'),
  ('Vietnam', 'Cu Chi Tunnels', 'spot', 11.1425, 106.4640, 'The wartime tunnel network north-west of the city, a half-day trip each way.', '', 'editorial', 'vietnam:cu-chi-tunnels'),
  ('Vietnam', 'Binh Tay Market', 'shopping', 10.7500, 106.6503, 'Cholon''s wholesale market hall, the centre of Saigon''s Chinatown.', '', 'editorial', 'vietnam:binh-tay-market'),
  ('Vietnam', 'Thien Hau Temple', 'spot', 10.7533, 106.6580, 'Cantonese sea-goddess temple in Cholon, hung with slow-burning incense coils.', '', 'editorial', 'vietnam:thien-hau-temple'),
  ('Vietnam', 'Saigon Opera House', 'spot', 10.7770, 106.7030, 'French colonial theatre on Dong Khoi, still staging the AO Show most nights.', '', 'editorial', 'vietnam:saigon-opera-house'),
  ('Vietnam', 'Museum of Vietnamese History', 'spot', 10.7880, 106.7045, 'Cham sculpture and dynastic collections, next to the zoo and botanical garden.', '', 'editorial', 'vietnam:museum-of-vietnamese-history'),
  ('Vietnam', 'Saigon Railway Station', 'transport', 10.7823, 106.6775, 'Ga Sai Gon, terminus of the Reunification line running north to Hanoi.', '', 'editorial', 'vietnam:saigon-railway-station'),
  ('Malaysia', 'KL Tower', 'spot', 3.1528, 101.7038, 'Menara KL, whose deck sits higher than the Petronas skybridge and is easier to book.', '', 'editorial', 'malaysia:kl-tower'),
  ('Malaysia', 'Merdeka Square', 'spot', 3.1478, 101.6935, 'The colonial padang where independence was declared in 1957.', '', 'editorial', 'malaysia:merdeka-square'),
  ('Malaysia', 'Sultan Abdul Samad Building', 'spot', 3.1489, 101.6944, 'Moorish-style clocktower facing Merdeka Square, floodlit after dark.', '', 'editorial', 'malaysia:sultan-abdul-samad-building'),
  ('Malaysia', 'Masjid Jamek', 'spot', 3.1489, 101.6958, 'The old mosque at the river confluence; robes are lent free at the gate.', '', 'editorial', 'malaysia:masjid-jamek'),
  ('Malaysia', 'Petaling Street', 'shopping', 3.1436, 101.6980, 'Chinatown''s covered market street — bargaining expected, counterfeits everywhere.', '', 'editorial', 'malaysia:petaling-street'),
  ('Malaysia', 'Sri Mahamariamman Temple', 'spot', 3.1436, 101.6963, 'KL''s oldest Hindu temple, its gateway tower crowded with painted figures.', '', 'editorial', 'malaysia:sri-mahamariamman-temple'),
  ('Malaysia', 'National Mosque of Malaysia', 'spot', 3.1420, 101.6917, 'Masjid Negara, a 1960s modernist mosque under a folded blue roof.', '', 'editorial', 'malaysia:national-mosque-of-malaysia'),
  ('Malaysia', 'Islamic Arts Museum Malaysia', 'spot', 3.1418, 101.6893, 'Manuscripts, textiles and architectural models, beside the Lake Gardens.', '', 'editorial', 'malaysia:islamic-arts-museum-malaysia'),
  ('Malaysia', 'Perdana Botanical Garden', 'spot', 3.1425, 101.6869, 'The Lake Gardens, the city''s oldest park, with the bird park inside it.', '', 'editorial', 'malaysia:perdana-botanical-garden'),
  ('Malaysia', 'KL Bird Park', 'spot', 3.1435, 101.6869, 'Walk-through aviary in the Lake Gardens, billed as the world''s largest.', '', 'editorial', 'malaysia:kl-bird-park'),
  ('Malaysia', 'Thean Hou Temple', 'spot', 3.1220, 101.6870, 'Six-tiered Chinese temple on a hill south of the centre, hung with lanterns.', '', 'editorial', 'malaysia:thean-hou-temple'),
  ('Malaysia', 'Chow Kit Market', 'food', 3.1633, 101.6980, 'KL''s largest wet market, north of the centre and busiest early morning.', '', 'editorial', 'malaysia:chow-kit-market'),
  ('Malaysia', 'KL Sentral', 'transport', 3.1343, 101.6865, 'The main rail interchange and the KLIA Ekspres city terminus.', '', 'editorial', 'malaysia:kl-sentral'),
  ('Malaysia', 'Suria KLCC', 'shopping', 3.1580, 101.7118, 'The mall under the Petronas Towers, sitting on top of the LRT station.', '', 'editorial', 'malaysia:suria-klcc'),
  ('Malaysia', 'Putra Mosque Putrajaya', 'spot', 2.9364, 101.6890, 'The pink lakeside mosque at Putrajaya, an easy half-day out of the city.', '', 'editorial', 'malaysia:putra-mosque-putrajaya')
on conflict (destination, name) where created_by is null
do update set content_slug = excluded.content_slug;
