import type { ItemSeed } from './schema';

/**
 * 3–5 items per listing across the day counts and data sizes we actually sell.
 *
 * Every quirk here is deliberate and matches the real API:
 *   • `price` is a string of VND minor-unit-free integers — "177415", not 177415
 *   • `days` is zero-padded — "03", not 3
 *   • unlimited packages carry "UNGB" or "UNLI" where a size belongs
 *   • `itemCode` looks structured but is not — do not parse it
 *
 * The `_FAIL` / `_SLOW` / `_HANG` suffixes drive the fulfilment failure
 * injection in fulfillment.ts, so failure tests are deterministic.
 */
export const ITEM_SEED: ItemSeed[] = [
  // ── Cambodia ───────────────────────────────────────────────────────────────
  {
    listingCode: 'LKHM01',
    itemCode: 'EKHM3DPY01GB03D',
    itemName: 'Cambodia 1GB/day - 3 days',
    status: 'Active',
    days: '03',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '177415',
  },
  {
    listingCode: 'LKHM01',
    itemCode: 'EKHM5DPY01GB05D',
    itemName: 'Cambodia 1GB/day - 5 days',
    status: 'Active',
    days: '05',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '284830',
  },
  {
    listingCode: 'LKHM01',
    itemCode: 'EKHM7DPY02GB07D',
    itemName: 'Cambodia 2GB/day - 7 days',
    status: 'Active',
    days: '07',
    data: '02GB',
    dataAmountValue: '02',
    dataAmountUnit: 'GB',
    price: '512900',
  },
  {
    listingCode: 'LKHM01',
    itemCode: 'EKHM15DPY01GB15D',
    itemName: 'Cambodia 1GB/day - 15 days',
    status: 'Active',
    days: '15',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '798500',
  },
  {
    listingCode: 'LKHM01',
    itemCode: 'EKHM30DPY02GB30D',
    itemName: 'Cambodia 2GB/day - 30 days',
    status: 'Active',
    days: '30',
    data: '02GB',
    dataAmountValue: '02',
    dataAmountUnit: 'GB',
    price: '1874300',
  },

  // ── Fulfilment failure injection. Same product, deterministic outcomes. ─────
  {
    listingCode: 'LKHM01',
    itemCode: 'EKHM3DPY01GB03D_FAIL',
    itemName: 'Cambodia 1GB/day - 3 days (fulfilment always fails)',
    status: 'Active',
    days: '03',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '177415',
  },
  {
    listingCode: 'LKHM01',
    itemCode: 'EKHM3DPY01GB03D_SLOW',
    itemName: 'Cambodia 1GB/day - 3 days (60 second fulfilment)',
    status: 'Active',
    days: '03',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '177415',
  },
  {
    listingCode: 'LKHM01',
    itemCode: 'EKHM3DPY01GB03D_HANG',
    itemName: 'Cambodia 1GB/day - 3 days (webhook never fires)',
    status: 'Active',
    days: '03',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '177415',
  },

  // ── Thailand ───────────────────────────────────────────────────────────────
  {
    listingCode: 'LTHA01',
    itemCode: 'ETHA3DPY01GB03D',
    itemName: 'Thailand 1GB/day - 3 days',
    status: 'Active',
    days: '03',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '165000',
  },
  {
    listingCode: 'LTHA01',
    itemCode: 'ETHA5DPY02GB05D',
    itemName: 'Thailand 2GB/day - 5 days',
    status: 'Active',
    days: '05',
    data: '02GB',
    dataAmountValue: '02',
    dataAmountUnit: 'GB',
    price: '355000',
  },
  {
    listingCode: 'LTHA01',
    itemCode: 'ETHA10DPY02GB10D',
    itemName: 'Thailand 2GB/day - 10 days',
    status: 'Active',
    days: '10',
    data: '02GB',
    dataAmountValue: '02',
    dataAmountUnit: 'GB',
    price: '645000',
  },
  {
    listingCode: 'LTHA01',
    itemCode: 'ETHA30DPY03GB30D',
    itemName: 'Thailand 3GB/day - 30 days',
    status: 'Active',
    days: '30',
    data: '03GB',
    dataAmountValue: '03',
    dataAmountUnit: 'GB',
    price: '1785000',
  },

  // ── Vietnam (fixed data, KYC) ──────────────────────────────────────────────
  {
    listingCode: 'LVNM01',
    itemCode: 'EVNM05GBFX07D',
    itemName: 'Vietnam 5GB - 7 days',
    status: 'Active',
    days: '07',
    data: '05GB',
    dataAmountValue: '05',
    dataAmountUnit: 'GB',
    price: '298000',
  },
  {
    listingCode: 'LVNM01',
    itemCode: 'EVNM10GBFX15D',
    itemName: 'Vietnam 10GB - 15 days',
    status: 'Active',
    days: '15',
    data: '10GB',
    dataAmountValue: '10',
    dataAmountUnit: 'GB',
    price: '512000',
  },
  {
    listingCode: 'LVNM01',
    itemCode: 'EVNM30GBFX30D',
    itemName: 'Vietnam 30GB - 30 days',
    status: 'Active',
    days: '30',
    data: '30GB',
    dataAmountValue: '30',
    dataAmountUnit: 'GB',
    price: '985000',
  },
  // Withdrawn SKU. Still returned by /api/items, must never be sellable.
  {
    listingCode: 'LVNM01',
    itemCode: 'EVNM03GBFX05D',
    itemName: 'Vietnam 3GB - 5 days (withdrawn)',
    status: 'InActive',
    days: '05',
    data: '03GB',
    dataAmountValue: '03',
    dataAmountUnit: 'GB',
    price: '215000',
  },

  // ── Singapore ──────────────────────────────────────────────────────────────
  {
    listingCode: 'LSGP01',
    itemCode: 'ESGP3DPY01GB03D',
    itemName: 'Singapore 1GB/day - 3 days',
    status: 'Active',
    days: '03',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '210000',
  },
  {
    listingCode: 'LSGP01',
    itemCode: 'ESGP5DPY02GB05D',
    itemName: 'Singapore 2GB/day - 5 days',
    status: 'Active',
    days: '05',
    data: '02GB',
    dataAmountValue: '02',
    dataAmountUnit: 'GB',
    price: '398000',
  },
  {
    listingCode: 'LSGP01',
    itemCode: 'ESGP10DPY02GB10D',
    itemName: 'Singapore 2GB/day - 10 days',
    status: 'Active',
    days: '10',
    data: '02GB',
    dataAmountValue: '02',
    dataAmountUnit: 'GB',
    price: '720000',
  },

  // ── Southeast Asia regional ────────────────────────────────────────────────
  {
    listingCode: 'LSTA01',
    itemCode: 'ESTA5DPY01GB05D',
    itemName: 'Southeast Asia 1GB/day - 5 days',
    status: 'Active',
    days: '05',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '325000',
  },
  {
    listingCode: 'LSTA01',
    itemCode: 'ESTA10DPY02GB10D',
    itemName: 'Southeast Asia 2GB/day - 10 days',
    status: 'Active',
    days: '10',
    data: '02GB',
    dataAmountValue: '02',
    dataAmountUnit: 'GB',
    price: '689000',
  },
  // Unlimited, spelled "UNGB" / "UN".
  {
    listingCode: 'LSTA01',
    itemCode: 'ESTA15DUNGB15D',
    itemName: 'Southeast Asia Unlimited - 15 days',
    status: 'Active',
    days: '15',
    data: 'UNGB',
    dataAmountValue: 'UN',
    dataAmountUnit: 'GB',
    price: '1290000',
  },
  {
    listingCode: 'LSTA01',
    itemCode: 'ESTA30DPY03GB30D',
    itemName: 'Southeast Asia 3GB/day - 30 days',
    status: 'Active',
    days: '30',
    data: '03GB',
    dataAmountValue: '03',
    dataAmountUnit: 'GB',
    price: '1950000',
  },

  // ── Asia regional (fixed) ──────────────────────────────────────────────────
  {
    listingCode: 'LASI01',
    itemCode: 'EASI05GBFX07D',
    itemName: 'Asia 5GB - 7 days',
    status: 'Active',
    days: '07',
    data: '05GB',
    dataAmountValue: '05',
    dataAmountUnit: 'GB',
    price: '545000',
  },
  {
    listingCode: 'LASI01',
    itemCode: 'EASI10GBFX15D',
    itemName: 'Asia 10GB - 15 days',
    status: 'Active',
    days: '15',
    data: '10GB',
    dataAmountValue: '10',
    dataAmountUnit: 'GB',
    price: '875000',
  },
  {
    listingCode: 'LASI01',
    itemCode: 'EASI20GBFX30D',
    itemName: 'Asia 20GB - 30 days',
    status: 'Active',
    days: '30',
    data: '20GB',
    dataAmountValue: '20',
    dataAmountUnit: 'GB',
    price: '1450000',
  },

  // ── Japan ──────────────────────────────────────────────────────────────────
  // Unlimited, spelled the other way GoHub spells it: "UNLI" / "UNLI".
  {
    listingCode: 'LJPN01',
    itemCode: 'EJPN5DUNLI05D',
    itemName: 'Japan Unlimited - 5 days',
    status: 'Active',
    days: '05',
    data: 'UNLI',
    dataAmountValue: 'UNLI',
    dataAmountUnit: 'GB',
    price: '690000',
  },
  {
    listingCode: 'LJPN01',
    itemCode: 'EJPN7DPY02GB07D',
    itemName: 'Japan 2GB/day - 7 days',
    status: 'Active',
    days: '07',
    data: '02GB',
    dataAmountValue: '02',
    dataAmountUnit: 'GB',
    price: '525000',
  },
  {
    listingCode: 'LJPN01',
    itemCode: 'EJPN10DPY03GB10D',
    itemName: 'Japan 3GB/day - 10 days',
    status: 'Active',
    days: '10',
    data: '03GB',
    dataAmountValue: '03',
    dataAmountUnit: 'GB',
    price: '845000',
  },
  {
    listingCode: 'LJPN01',
    itemCode: 'EJPN30DPY02GB30D',
    itemName: 'Japan 2GB/day - 30 days',
    status: 'Active',
    days: '30',
    data: '02GB',
    dataAmountValue: '02',
    dataAmountUnit: 'GB',
    price: '1985000',
  },

  // ── Global ─────────────────────────────────────────────────────────────────
  {
    listingCode: 'LGLO01',
    itemCode: 'EGLO01GBFX07D',
    itemName: 'Global 1GB - 7 days',
    status: 'Active',
    days: '07',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '545000',
  },
  {
    listingCode: 'LGLO01',
    itemCode: 'EGLO03GBFX15D',
    itemName: 'Global 3GB - 15 days',
    status: 'Active',
    days: '15',
    data: '03GB',
    dataAmountValue: '03',
    dataAmountUnit: 'GB',
    price: '1120000',
  },
  {
    listingCode: 'LGLO01',
    itemCode: 'EGLO10GBFX30D',
    itemName: 'Global 10GB - 30 days',
    status: 'Active',
    days: '30',
    data: '10GB',
    dataAmountValue: '10',
    dataAmountUnit: 'GB',
    price: '2680000',
  },

  // ── Item under the retired Malaysia listing ────────────────────────────────
  {
    listingCode: 'LMYS01',
    itemCode: 'EMYS5DPY01GB05D',
    itemName: 'Malaysia 1GB/day - 5 days',
    status: 'Active',
    days: '05',
    data: '01GB',
    dataAmountValue: '01',
    dataAmountUnit: 'GB',
    price: '245000',
  },
];
