import type { ListingSeed } from './schema';

/**
 * Eight active listings covering our launch destinations plus one InActive
 * listing so the filtering layer has something to drop.
 *
 * Only specifications that carry a value are listed here. Everything else in
 * S1–S21 is still emitted on the wire, as an empty string — which is what the
 * real API does and what our normalizer has to survive.
 */
export const LISTING_SEED: ListingSeed[] = [
  {
    listingCode: 'LKHM01',
    listingName: 'Cambodia Daily Data',
    status: 'Active',
    categoryCodes: ['KH', 'DATA'],
    specs: {
      S1: 'eSIM',
      S2: 'Cambodia',
      S3: 'Daily Data',
      S5: '4G',
      S6: 'Up to 4G LTE, throttled after daily allowance',
      S7: 'Yes',
      S8: 'Yes',
      S11: 'No',
      S15: 'No',
      S18: 'Yes',
      S20: 'Activates automatically within 5 minutes of connecting to a supported network.',
      S21: '30',
    },
  },
  {
    listingCode: 'LTHA01',
    listingName: 'Thailand Daily Data 5G',
    status: 'Active',
    categoryCodes: ['TH', 'DATA'],
    specs: {
      S1: 'eSIM',
      S2: 'Thailand',
      S3: 'Daily Data',
      S5: '5G',
      S7: 'Yes',
      S8: 'Yes',
      S11: 'No',
      // Long dial-code instruction, exactly the kind of string that breaks a
      // naive UI that assumes specification values are short labels.
      S13: 'Special activation required. After inserting the eSIM and connecting to the network, dial *151*3*1# and wait for the confirmation SMS before using data. If no SMS arrives within 10 minutes, dial *151# and select option 3, then option 1. The handset must be set to allow the eSIM line to place outgoing calls for this step, after which voice can be disabled again.',
      S15: 'No',
      S18: 'Yes',
      S20: 'Activates on first network attach, usually under 10 minutes.',
      S21: '30',
    },
  },
  {
    listingCode: 'LVNM01',
    listingName: 'Vietnam Fixed Data',
    status: 'Active',
    categoryCodes: ['VN', 'DATA_VOICE'],
    specs: {
      S1: 'eSIM',
      S2: 'Vietnam',
      S3: 'Fixed Data',
      S5: '4G',
      S7: 'Yes',
      S8: 'Yes',
      S9: 'Yes',
      S10: 'Yes',
      // KYC destination — passport registration before the line will carry data.
      S11: 'Yes',
      S12: 'https://kyc.example-gohub.test/vn/register',
      S15: 'Yes',
      S18: 'Yes',
      S19: 'Validity runs from first network attach, not from purchase.',
      S20: 'Activates after KYC approval, typically 30 minutes to 2 hours.',
      S21: '60',
    },
  },
  {
    listingCode: 'LSGP01',
    listingName: 'Singapore Daily Data 5G',
    status: 'Active',
    categoryCodes: ['SG', 'DATA'],
    specs: {
      S1: 'eSIM',
      S2: 'Singapore',
      S3: 'Daily Data',
      S5: '5G',
      S7: 'Yes',
      S8: 'Yes',
      S11: 'No',
      // Restriction note — must reach the customer before purchase, not after.
      S14: 'VoIP over this network is restricted by the local carrier. WhatsApp and Messenger voice or video calls may fail to connect; messaging is unaffected. Use a Wi-Fi network for calls.',
      S15: 'No',
      S18: 'Yes',
      S21: '30',
    },
  },
  {
    listingCode: 'LSTA01',
    listingName: 'Southeast Asia Regional',
    status: 'Active',
    categoryCodes: ['STA', 'SMT', 'DATA'],
    specs: {
      S1: 'eSIM',
      S2: 'Cambodia, Thailand, Vietnam, Laos, Malaysia, Singapore, Indonesia, Philippines',
      S3: 'Daily Data',
      S5: '4G',
      S7: 'Yes',
      S8: 'Yes',
      S11: 'No',
      S15: 'No',
      S16: 'On some Android handsets the APN must be set manually to `gohub` with no username or password before data will pass.',
      S17: 'https://support.example-gohub.test/apn/android,https://support.example-gohub.test/apn/ios',
      S18: 'Yes',
      S20: 'Activates on first network attach in any covered country.',
      S21: '30',
    },
  },
  {
    listingCode: 'LASI01',
    listingName: 'Asia Regional Fixed Data',
    status: 'Active',
    categoryCodes: ['ASI', 'DATA'],
    specs: {
      S1: 'eSIM',
      S2: 'Asia, 22 countries',
      S3: 'Fixed Data',
      S5: '4G',
      S7: 'Yes',
      S8: 'No',
      S11: 'No',
      S15: 'No',
      S18: 'No',
      S19: 'Allowance is shared across all covered countries.',
      S21: '60',
    },
  },
  {
    listingCode: 'LJPN01',
    listingName: 'Japan Daily Data 5G',
    status: 'Active',
    categoryCodes: ['JP', 'DATA'],
    specs: {
      S1: 'eSIM',
      S2: 'Japan',
      S3: 'Daily Data',
      S5: '5G',
      S7: 'Yes',
      S8: 'Yes',
      S11: 'No',
      S15: 'No',
      S18: 'Yes',
      S20: 'Activates within 3 minutes of attaching to a Japanese network. Install before departure; activation only begins on arrival.',
      S21: '30',
    },
  },
  {
    listingCode: 'LGLO01',
    listingName: 'Global Fixed Data',
    status: 'Active',
    categoryCodes: ['GLO', 'DATA'],
    specs: {
      S1: 'eSIM',
      S2: 'Global, 120+ countries',
      S3: 'Fixed Data',
      S5: '4G',
      S7: 'Yes',
      S8: 'Yes',
      S11: 'No',
      S15: 'No',
      S16: 'Set the APN to `global.gohub` manually if data does not pass within 5 minutes of activation.',
      S17: 'https://support.example-gohub.test/apn/global',
      S18: 'Yes',
      S21: '60',
    },
  },
  // Retired listing. Present in the API, must never reach a product page.
  {
    listingCode: 'LMYS01',
    listingName: 'Malaysia Daily Data (retired)',
    status: 'InActive',
    categoryCodes: ['MY', 'DATA'],
    specs: {
      S1: 'eSIM',
      S2: 'Malaysia',
      S3: 'Daily Data',
      S5: '4G',
      S11: 'No',
      S21: '30',
    },
  },
];
